### ISSUE TITLE
我在linux上安装fruitbat后计算Luminosity Distance等无法运行

### ISSUE THREAD

**Issue by kongjunZhang** [abatten/fruitbat#48] opened 2021-12-13 13:23 UTC
![2021-12-13 21-15-29屏幕截图](https://user-images.githubusercontent.com/51732190/145820271-2ad1034d-3af8-4d88-b6e1-26e2c7fbf199.png)

**Comment by kongjunZhang** [comment] 2021-12-13 13:24
Comoving Distance，Luminosity Distance也无法运行没有结果

**Comment by abatten** [comment] 2021-12-14 02:40
Hi @610069895, thank you for submitting a bug report. 

It seems to me that the function `calc_luminosity_distance` is missing something. To calculate the energy of an FRB, it will need a redshift (measured or estimated). Are you able to provide the full code that you have used to produce this error? I have tried to replicate something similar to yours but get the following:

```
In [1]: import fruitbat

In [2]: frb = fruitbat.Frb(1000)

In [3]: frb.fluence = 2.0

In [4]: frb.obs_freq_central = 1600

In [5]: frb.calc_redshift()
Out[5]: <Quantity 0.98344417>

In [6]: frb.calc_energy()
Out[6]: <Quantity 8.53026964e+40 erg>
```
I'm interested to see what parameters you have used for `frb`, and any functions you have run.

**Comment by kongjunZhang** [comment] 2021-12-14 02:57
我在linux上能计算红移，但是其他参数报错
------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "abatten/fruitbat"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Dec 14, 2021 10:40 AM
***@***.***&gt;;
Cc:&nbsp;"Zhang ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [abatten/fruitbat] 我在linux上安装fruitbat后计算Luminosity Distance等无法运行 (Issue #48)





 
Hi @610069895, thank you for submitting a bug report.
 
It seems to me that the function calc_luminosity_distance is missing something. To calculate the energy of an FRB, it will need a redshift (measured or estimated). Are you able to provide the full code that you have used to produce this error? I have tried to replicate something similar to yours but get the following:
 In [1]: import fruitbat In [2]: frb = fruitbat.Frb(1000) In [3]: frb.fluence = 2.0 In [4]: frb.obs_freq_central = 1600 In [5]: frb.calc_redshift() Out[5]: <Quantity 0.98344417&gt; In [6]: frb.calc_energy() Out[6]: <Quantity 8.53026964e+40 erg&gt;  
I'm interested to see what parameters you have used for frb, and any functions you have run.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by abatten** [comment] 2021-12-15 03:56
If you can provide the rest of the code that you have used to get this output, that would be useful to help find the cause of this issue.

**Comment by abatten** [comment] 2023-07-05 11:57
I'm going to close this because there have been no updates in over two years.

**Closed as completed by abatten** 2023-07-05 11:57 UTC
Labels: bug
